version: "3.1"

services:
  docker-reactive-springboot:
    build: .
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always